apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  template:
    spec:
      containers:
      - name: server
        image: myapp:0.0.1
        ports:
        - containerPort: 8080
        env:
        - name: ENVIRONMENT
          value: "my environment"
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
